version: '3.4'

services:
  exchangeaccess.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44359
    ports:
      - "61059:80"
      - "44359:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  trendanalysis.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44398
    ports:
      - "54270:80"
      - "44398:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  investing.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44398
    ports:
      - "54790:80"
      - "44320:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  rabbitmq:
    ports:
      - "8080:15672"  # Important: In a production environment your should remove the external port
      - "5672:5672"    # Important: In a production environment your should remove the external port
      - "5671:5671"
      - "15671:15671"
      - "4369:4369"

  sql.data:
    environment:
      - MSSQL_SA_PASSWORD=1Secure*Password1
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "5432:1433"   # Important: In a production environment your should remove the external port

